parameters:
#    umbrella_admin.example.class: Umbrella\AdminBundle\Example

services:
#    umbrella_admin.example:
#        class: %umbrella_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
