umbrella_auth:
    resource: "@UmbrellaAuthBundle/Resources/config/routing.yml"
    prefix:   /

umbrella_frontend:
    resource: "@UmbrellaFrontendBundle/Resources/config/routing.yml"
    prefix:   /frontend

umbrella_admin:
    resource: "@UmbrellaAdminBundle/Resources/config/routing.yml"
    prefix:   /admin
