'Umbrella\AdminBundle\Entity\Profile':
    type: entity
    table: profile
    fields:
        profileID:
            type: integer
            id: true
            generator:
                strategy: AUTO
        email:
            type: string
            lenght: 255
        password:
            type: string
            lenght: 32
        firstName:
            type: string
            lenght: 255
        lastName:
            type: string
            lenght: 255
        homePhone:
            type: string
            lenght: 255
        cellPhone:
            type: string
            lenght: 255
        altPhone:
            type: string
            lenght: 255
    lifecycleCallbacks: {  }
